---
- name: "show remote environment"
  shell: env

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: true

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: install dependencies, such as NodeJS and NPM
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: true

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Configure server with env variables
  command: |
        echo NODE_ENV=production > ~/project/backend/.env
        echo TYPEORM_CONNECTION=postgres >> ~/project/backend/.env
        echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ~/project/backend/.env
        echo TYPEORM_HOST=udapeople-database1.c2qxjxanfw6n.us-east-1.rds.amazonaws.com >> ~/project/backend/.env
        echo TYPEORM_PORT=5432 >> ~/project/backend/.env
        echo TYPEORM_USERNAME=udapeople >> ~/project/backend/.env
        echo TYPEORM_PASSWORD=udapeople >> ~/project/backend/.env
        echo TYPEORM_DATABASE=udapeople >> ~/project/backend/.env
        echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ~/project/backend/.env
        echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ~/project/backend/.env

        cat ~/project/backend/.env
