---
  - name: "The remote environment"
    shell: env

  - name: "copy artifact to EC2 backend"
    become: yes
    synchronize:
      src: "files/artifact.tar.gz"
      dest: ~/
      recursive: true

  - name: "Extract Artifact"
    become: yes
    shell: |
        tar -xvfz artifact.tar.gz

  - name: "start server"
    become: true
    shell: | 
             npm install
             pm2 stop default
             sudo pm2 start npm -- start