---
  - name: "The remote environment"
    shell: env

  - name: "copy zipped archive"
    become: true
    synchronize:
      src: ../../artifact.tar.gz
      dest: ~/artifact.tar.gz
      recursive: true

  - name: Creates directory
    become: true
    shell: |
        mkdir backend_app

  - name: "extract artifact into backend_app"
    become: true
    shell: |
            cp artifact.tar.gz backend_app
            cd backend_app
            tar xzvf artifact.tar.gz

  - name: Install dependencies
    become: true
    args:
      chdir: backend_app
    shell: npm install

  - name: "start server"
    become: true
    shell: |
            cd backend_app
            pm2 stop default
            sudo pm2 start npm -- start 
    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

# - name: "show remote environment"
#     shell: env

#   - name: "copy backend binaries"
#     become: yes
#     synchronize:
#       src: ../../backend/dist
#       dest: /home/ubuntu/uda_app
#       recursive: true

#   - name: "copy node_modules"
#     become: yes
#     synchronize:
#       src: ../../backend/node_modules
#       dest: /home/ubuntu/uda_app
#       recursive: true

#   - name: "delete anything that might already be running"
#     become: true
#     command: pm2 delete all
#     ignore_errors: true

#   - name: "start server"
#     become: true
#     shell: |
#         cd ~/uda_app/dist
#         npm install
#         pm2 stop default
#         sudo pm2 start -f ./main.js