---
  - name: "The remote environment"
    shell: env

  - name: "copy zipped archive"
    become: true
    synchronize:
      src: ../../artifact.tar.gz
      dest: ~/
      recursive: true

  - name: Creates directory
    file:
      path: ~/backend_app
      state: directory

  - name: "extract artifact into backend_app"
    become: true
    shell: |
            cp artifact.tar.gz backend_app
            cd backend_app
            tar xzvf artifact.tar.gz

  - name: "start server"
    become: true
    shell: |
            cd backend_app
            npm install
            pm2 stop default
            pm2 start npm -- start
